spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/${DB_NAME:softwaveco-reservation-system}
    username: ${DB_USERNAME:sums_admin}
    password: ${DB_PASS:admin}